package boxordering;

import java.awt.Dialog.ModalityType;
import javax.swing.JOptionPane;

public class MainMenu extends javax.swing.JFrame {

    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addbox = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addbox.setText("Add Box");
        addbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addboxActionPerformed(evt);
            }
        });

        jLabel1.setText("Flex Box Ordering System");

        jButton1.setText("Clear Box");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(addbox))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(addbox)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel() {
        setVisible(true);
        JOptionPane.showMessageDialog(null,
                "The 'Add box' operation has been cancelled.",
                "Cancellation",
                JOptionPane.INFORMATION_MESSAGE);
    }

    private void addboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addboxActionPerformed

        Box box;
        int cardboardGrade;
        double width, length, height;
        boolean sealable;
        int colourType;

        setVisible(false);

        BasicInfoForm infoForm = new BasicInfoForm();
        infoForm.setVisible(true);
        if (!infoForm.isValid()) {
            cancel();
            return;
        }
        BasicInfoFormResult infoResult = (BasicInfoFormResult) infoForm.getInfo();
        cardboardGrade = infoResult.grade;
        width = infoResult.width;
        height = infoResult.height;
        length = infoResult.length;
        sealable = infoResult.sealable;

        // with a cardboardGrade of 1, the user cannot have any colour.
        if (cardboardGrade == 1) {
            JOptionPane.showMessageDialog(null, "You will have no colours.", "Information", JOptionPane.INFORMATION_MESSAGE);
            colourType = 0;
            box = new BasicBox(width, length, height, cardboardGrade, sealable);

            // with a cardboardGrade of 5, the user must have two colours.
        } else if (cardboardGrade == 5) {
            JOptionPane.showMessageDialog(null, "You will have two colours.", "Information", JOptionPane.INFORMATION_MESSAGE);
            colourType = 2;

            // any other cardboardGrade, the user can choose what colour they want.
        } else {
            ColourForm colourForm = new ColourForm();
            colourForm.setVisible(true);
            if (!colourForm.isValid()) {
                cancel();
                return;
            }
            colourType = (int) colourForm.getInfo();
        }

        if (cardboardGrade <= 3 && colourType == 0) {
            box = new BasicBox(width, length, height, cardboardGrade, sealable);
        }

        if (colourType != 0) {
            if (colourType == 1) {
                box = new ColourBox(width, length, height, cardboardGrade, sealable, colourType);
            } else {
                
            }
        }

        System.out.println(box);

        setVisible(true);
    }//GEN-LAST:event_addboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
